# Configure interaction methods
[[interaction]]
    type = "Button"
    button-style = "SUCCESS"
    button-text = "ðŸ˜‹ Create Ticket"
    button-id = "btn2"
    action-ids = [
        "MyAction1",
        "MyAction2"
    ]

[[interaction]]
    type = "Button"
    button-style = "SUCCESS"
    button-text = "Create Ticket"
    button-id = "btn2"
    action-ids = [
        "MyAction1",
        "MyAction2"
    ]